envVarGroups:
  - name: data-aggregator

databases:
  - name: data-aggregator-postgres

services:
  - type: redis
    name: data-aggregator-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: []

  - type: web
    name: data-aggregator
    env: docker
    buildCommand: go build -tags netgo -ldflags '-s -w' -o server
    startCommand: ./server
    plan: starter
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: data-aggregator-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: data-aggregator-postgres
          property: connectionString

  - type: worker
    name: data-aggregator-worker
    env: docker
    buildCommand: go build -tags netgo -ldflags '-s -w' -o ./worker/worker
    startCommand: ./worker/worker
    plan: starter
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: data-aggregator-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: data-aggregator-postgres
          property: connectionString
